/**
 * Digicatch
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Player } from '../model/player';
import { PlayerPageDto } from '../model/playerPageDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class PlayersApiClient {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param filter pass in field:value field is a field on the model, value is string contained in the property of the model
     * @param page 
     * @param pageSize 
     * @param include 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public playersGet(filter?: Array<string>, page?: number, pageSize?: number, include?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<PlayerPageDto>;
    public playersGet(filter?: Array<string>, page?: number, pageSize?: number, include?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PlayerPageDto>>;
    public playersGet(filter?: Array<string>, page?: number, pageSize?: number, include?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PlayerPageDto>>;
    public playersGet(filter?: Array<string>, page?: number, pageSize?: number, include?: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (filter) {
            queryParameters = queryParameters.set('filter', filter.join(COLLECTION_FORMATS['csv']));
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (include) {
            queryParameters = queryParameters.set('include', include.join(COLLECTION_FORMATS['csv']));
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            const header = this.configuration.apiKeys["Authorization"];
            const headerString = typeof header  === 'function'
                ? header() : header;
            headers = headers.set('Authorization', headerString);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PlayerPageDto>(`${this.configuration.basePath}/players`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public playersIdDelete(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public playersIdDelete(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public playersIdDelete(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public playersIdDelete(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling playersIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            const header = this.configuration.apiKeys["Authorization"];
            const headerString = typeof header  === 'function'
                ? header() : header;
            headers = headers.set('Authorization', headerString);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.configuration.basePath}/players/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param friend 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public playersIdFriendsFriendDelete(friend: string, id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public playersIdFriendsFriendDelete(friend: string, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public playersIdFriendsFriendDelete(friend: string, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public playersIdFriendsFriendDelete(friend: string, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (friend === null || friend === undefined) {
            throw new Error('Required parameter friend was null or undefined when calling playersIdFriendsFriendDelete.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling playersIdFriendsFriendDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            const header = this.configuration.apiKeys["Authorization"];
            const headerString = typeof header  === 'function'
                ? header() : header;
            headers = headers.set('Authorization', headerString);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.configuration.basePath}/players/${encodeURIComponent(String(id))}/friends/${encodeURIComponent(String(friend))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param friend 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public playersIdFriendsFriendPost(friend: string, id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public playersIdFriendsFriendPost(friend: string, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public playersIdFriendsFriendPost(friend: string, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public playersIdFriendsFriendPost(friend: string, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (friend === null || friend === undefined) {
            throw new Error('Required parameter friend was null or undefined when calling playersIdFriendsFriendPost.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling playersIdFriendsFriendPost.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            const header = this.configuration.apiKeys["Authorization"];
            const headerString = typeof header  === 'function'
                ? header() : header;
            headers = headers.set('Authorization', headerString);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.configuration.basePath}/players/${encodeURIComponent(String(id))}/friends/${encodeURIComponent(String(friend))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public playersIdFriendsGet(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public playersIdFriendsGet(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public playersIdFriendsGet(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public playersIdFriendsGet(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling playersIdFriendsGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            const header = this.configuration.apiKeys["Authorization"];
            const headerString = typeof header  === 'function'
                ? header() : header;
            headers = headers.set('Authorization', headerString);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.configuration.basePath}/players/${encodeURIComponent(String(id))}/friends`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public playersIdGet(id: string, observe?: 'body', reportProgress?: boolean): Observable<Player>;
    public playersIdGet(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Player>>;
    public playersIdGet(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Player>>;
    public playersIdGet(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling playersIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            const header = this.configuration.apiKeys["Authorization"];
            const headerString = typeof header  === 'function'
                ? header() : header;
            headers = headers.set('Authorization', headerString);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Player>(`${this.configuration.basePath}/players/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param player 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public playersIdPut(id: string, player: Player, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public playersIdPut(id: string, player: Player, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public playersIdPut(id: string, player: Player, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public playersIdPut(id: string, player: Player, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling playersIdPut.');
        }
        if (player === null || player === undefined) {
            throw new Error('Required parameter player was null or undefined when calling playersIdPut.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            const header = this.configuration.apiKeys["Authorization"];
            const headerString = typeof header  === 'function'
                ? header() : header;
            headers = headers.set('Authorization', headerString);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.configuration.basePath}/players/${encodeURIComponent(String(id))}`,
            player,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param player 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public playersMePut(player: Player, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public playersMePut(player: Player, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public playersMePut(player: Player, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public playersMePut(player: Player, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (player === null || player === undefined) {
            throw new Error('Required parameter player was null or undefined when calling playersMePut.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            const header = this.configuration.apiKeys["Authorization"];
            const headerString = typeof header  === 'function'
                ? header() : header;
            headers = headers.set('Authorization', headerString);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.configuration.basePath}/players/me`,
            player,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param player 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public playersPost(player: Player, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public playersPost(player: Player, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public playersPost(player: Player, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public playersPost(player: Player, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (player === null || player === undefined) {
            throw new Error('Required parameter player was null or undefined when calling playersPost.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            const header = this.configuration.apiKeys["Authorization"];
            const headerString = typeof header  === 'function'
                ? header() : header;
            headers = headers.set('Authorization', headerString);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.configuration.basePath}/players`,
            player,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
