/**
 * Tour Guide API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Waypoint } from './waypoint';


export interface Tour { 
    readonly id: string;
    name: string;
    description: string;
    readonly waypoints: Array<Waypoint>;
}

