/**
 * Digicatch
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalUserSchema } from './localUserSchema';


export interface User { 
    readonly id: string;
    readonly name?: string;
    role: User.RoleEnum;
    local: LocalUserSchema;
    readonly deleted: boolean;
    readonly updatedAt: string;
}
export namespace User {
    export type RoleEnum = 'admin' | 'user';
    export const RoleEnum = {
        Admin: 'admin' as RoleEnum,
        User: 'user' as RoleEnum
    };
}

